application: ntu-taiwan-weather
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: css
  
- url: /image
  static_dir: image
  
- url: /js
  static_dir: js

- url: /tool/(memcache)
  script: MainHandler.py
  
- url: /
  script: MainHandler.py
  
- url: /.*
  script: NotFoundHandler.py
